name: Log Repository Full Paths

on:
  push:
    branches:
      - main

jobs:
  log-repo-full-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log Full File Paths
        env:
          REPO_URL: https://github.com/${{ github.repository }}
        run: |
          echo "Listing files with full GitHub paths:"
          find $GITHUB_WORKSPACE -type f | while read FILE; do
            # Convert absolute file paths to relative paths
            RELATIVE_PATH=$(realpath --relative-to=$GITHUB_WORKSPACE "$FILE")
            # Output the full GitHub URL for each file
            echo "$REPO_URL/$RELATIVE_PATH"
          done
