name: Log Repository Content

on:
  push:
    branches:
      - main

jobs:
  list-repo-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Environment Variables and Paths
        run: |
          echo "Home directory: $HOME"
          echo "Working directory: $GITHUB_WORKSPACE"
          echo "Temporary directory: $RUNNER_TEMP"
          echo "PATH: $PATH"

      - name: List Repository Content
        run: |
          echo "Listing repository content:"
          ls -la $GITHUB_WORKSPACE

      - name: List Nested Files (Optional)
        run: |
          echo "Detailed file structure (up to 2 levels):"
          find $GITHUB_WORKSPACE -maxdepth 2
